{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gamelog-api.fullname" . }}
  labels:
    {{- include "gamelog-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gamelog-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: http
          protocol: TCP
{{- end }}
